### ISSUE TITLE
update kiln deployment v0.1.19

### ISSUE THREAD

**Issue by noahdietz** [30x/shipyard-integration-test#1]
- [ ] change `edge/paths.basePath=/organizations` 
- [ ] add `DEPLOY_STATE=DEV_CONTAINER`
- [ ] add `0.1.19` image version
- [ ] add `DOCKER_REGISTRY_URL` and set to whatever you want, its just a tag when using local daemon's registry
- [ ] remove `POD_PROVIDER`
- [ ] remove `LOCAL_DIR`
- [ ] remove `LOCAL_REGISTRY_ONLY` (this made more sense when we used PTS_URLs)

These are things that are in the deployment file that are extraneous to `kiln`. Remove if you'd like, or don't, I trust your judgement.
- [ ] `ROUTABLE_LABEL_SELECTOR`
- [ ] `HOSTS_ANNOTATION`
- [ ] `ENV_LABEL`
- [ ] `PATHS_ANNOTATION`
- [ ] `APP_REV_LABEL`

**Comment by AdamMagaluk** [comment]
Changes in master now.
