### ISSUE TITLE
enrober needs DOCKER_REGISTRY_URL

### ISSUE THREAD

**Issue by noahdietz** [30x/shipyard-integration-test#2]
Whenever you upgrade to `v0.7.0` I think you'll need to add this env var to the enrober deployment.

On the cloud it gets this value from a docker.config secret, but in minikube its value doesn't mean anything, just necessary for tagging/finding images.

Make sure it's the same as the one on `kiln`...put it in the ConfigMap if you'd like, doesn't matter. But in the cloud, the ConfigMap won't be able to provide it.

**Comment by AdamMagaluk** [comment]
Why in the cloud the ConfigMap wont be able to provide it?

**Comment by noahdietz** [comment]
Can the ConfigMap reference a secret? If so, we should do that

**Comment by AdamMagaluk** [comment]
Not sure but we could populate a ENV for both enrober and kiln from a shared secret

**Comment by noahdietz** [comment]
Right right, they will share the same secret when deployed in the cloud. But for minikube, that secret doesn't exist, so we can put it wherever you'd like, so long as they are the same
