### ISSUE TITLE
enable deleting in local registry

### ISSUE THREAD

**Issue by noahdietz** [30x/shipyard-integration-test#4]
Can we enable image deletion in the registry we host on here?

Per [this conversation](https://github.com/docker/distribution/issues/1326) we need to add the following environment variable to the deployment
```yaml
- name: REGISTRY_STORAGE_DELETE_ENABLED
  value: "true"
```

I've tested it, prior to this being added, the API call returned a `405 Method Not Allowed`, and that error went away after the added configuration.

Thanks!

**Comment by AdamMagaluk** [comment]
Sounds good, ill get a PR for this and the other issue with order of bring up.

**Comment by AdamMagaluk** [comment]
See master.
